name: Deploy
on:
  push:
    branches: [ static-site-to-aws ]
permissions:
  contents: read

jobs:
  Deploy-static-site:
    runs-on: ubuntu-latest
    environment: # This publishes your URL on your repo environment
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy-site.outputs.public_url }}

    steps:
    - id: deploy-site
      uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        tf_action: 'apply'
        tf_state_bucket_destroy: true # If destroying, will remove the bucket

        aws_site_cdn_enabled: false # Takes more time to deploy and not needed for example
        aws_r53_domain_name: bitovi-sandbox.com # You should own and have this domain available in R53
        aws_r53_sub_domain_name: static-site
        aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain
