
name: Deploy-GCP

on:
  push:
    branches: [ gcp-test ]

permissions:
  contents: read

jobs:
  GCP-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-gcp@wip1
      with:
        gcp_secret_access_key: ${{ secrets.GCP_SECRET_ACCESS_KEY }}
        gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
        app_port: 3000


# run locally with act!
# brew install act
# act -W .github/workflows/deploy-gcp.yaml