name: Destroy-PR

on:
  pull_request:
    types: [ closed ]
    
permissions:
  contents: read
  
jobs:
  EC2-Destroy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: destroy
        name: Destroy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
          aws_default_region: us-east-1
          app_port: 3000
          stack_destroy: true
          # Uncomment this to delete the bucket used to store Terraform state files
          tf_state_bucket_destroy: true