name: GPT Explain PR

on:
  pull_request:
    branches: [ main ]

env:
  DIFF: ${{ compare(github.base_ref, github.head_ref) }}

jobs:
  explain-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Explain Diff
      id: explain
      uses: thecloudlore/explain-diff@v0.2
      with:
        diff: ${{ env.DIFF }}
        apikey: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Post Comment
      if: steps.explain.outputs.explanation
      uses: actions/github-script@v6
      with:
        script: |
          const octokit = require('@octokit/rest')({ auth: process.env.GITHUB_TOKEN });
          octokit.pulls.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: steps.explain.outputs.explanation
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}