name: GPT Review PR

on: [pull_request]

jobs:
  gpt-review-pr:
    runs-on: ubuntu-latest
    name: GPT Review PR
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - id: diff
        run: |
          git fetch origin main
          diff=$(git diff origin/main)
          echo $diff
          echo "DIFF=$(echo $diff)" >> $GITHUB_ENV
      - id: review
        uses: samjhill/GPTReview@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          REPOSITORY_NAME: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DIFF: ${{ env.DIFF }}